<a href="https://colab.research.google.com/github/mb16biswas/simple_ai_chatbot/blob/main/simple_chat_bot_29_01_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
#source of the data
# https://www.techwithtim.net/tutorials/ai-chatbot/part-1/
a = {"intents": [
        {"tag": "greeting",
         "patterns": ["Hi", "How are you", "Is anyone there?", "Hello", "Good day"],
         "responses": ["Hello, thanks for visiting", "Good to see you again", "Hi there, how can I help?"],
         "context_set": ""
        },
        {"tag": "goodbye",
         "patterns": ["Bye", "See you later", "Goodbye"],
         "responses": ["See you later, thanks for visiting", "Have a nice day", "Bye! Come back again soon."]
        },
        {"tag": "thanks",
         "patterns": ["Thanks", "Thank you", "That's helpful"],
         "responses": ["Happy to help!", "Any time!", "My pleasure"]
        },
        {"tag": "hours",
         "patterns": ["What hours are you open?", "What are your hours?", "When are you open?" ],
         "responses": ["We're open every day 9am-9pm", "Our hours are 9am-9pm every day"]
        },
        {"tag": "payments",
         "patterns": ["Do you take credit cards?", "Do you accept Mastercard?", "Are you cash only?" ],
         "responses": ["We accept VISA, Mastercard and AMEX", "We accept most major credit cards"]
        },
        {"tag": "opentoday",
         "patterns": ["Are you open today?", "When do you open today?", "What are your hours today?"],
         "responses": ["We're open every day from 9am-9pm", "Our hours are 9am-9pm every day"]
        }
   ]
}

In [110]:
store = a 

In [2]:
import tensorflow as tf

from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
import numpy as np 


**Data processing ......**

In [5]:
store = a["intents"]

In [6]:
d = []
for i in range(len(store)) : 
  c = store[i]["patterns"]
  for j in range(len(c)):
    d.append(c[j].lower())
 

In [ ]:
d

['hi',
 'how are you',
 'is anyone there?',
 'hello',
 'good day',
 'bye',
 'see you later',
 'goodbye',
 'thanks',
 'thank you',
 "that's helpful",
 'what hours are you open?',
 'what are your hours?',
 'when are you open?',
 'do you take credit cards?',
 'do you accept mastercard?',
 'are you cash only?',
 'are you open today?',
 'when do you open today?',
 'what are your hours today?']

In [11]:
tokenizer = Tokenizer()
tokenizer = Tokenizer()



corpus =  d 

tokenizer.fit_on_texts(corpus)
tokenizer.fit_on_texts(corpus)
total_words = len(tokenizer.word_index) + 1
total_words= len(tokenizer.word_index) + 1 

print(tokenizer.word_index)
print(tokenizer.word_index)
print(total_words)

{'you': 1, 'are': 2, 'open': 3, 'what': 4, 'hours': 5, 'do': 6, 'today': 7, 'your': 8, 'when': 9, 'hi': 10, 'how': 11, 'is': 12, 'anyone': 13, 'there': 14, 'hello': 15, 'good': 16, 'day': 17, 'bye': 18, 'see': 19, 'later': 20, 'goodbye': 21, 'thanks': 22, 'thank': 23, "that's": 24, 'helpful': 25, 'take': 26, 'credit': 27, 'cards': 28, 'accept': 29, 'mastercard': 30, 'cash': 31, 'only': 32}
{'you': 1, 'are': 2, 'open': 3, 'what': 4, 'hours': 5, 'do': 6, 'today': 7, 'your': 8, 'when': 9, 'hi': 10, 'how': 11, 'is': 12, 'anyone': 13, 'there': 14, 'hello': 15, 'good': 16, 'day': 17, 'bye': 18, 'see': 19, 'later': 20, 'goodbye': 21, 'thanks': 22, 'thank': 23, "that's": 24, 'helpful': 25, 'take': 26, 'credit': 27, 'cards': 28, 'accept': 29, 'mastercard': 30, 'cash': 31, 'only': 32}
33


In [8]:

token_list = tokenizer.texts_to_sequences([corpus[2]])[0]

In [9]:
token_list

[12, 13, 14]

In [10]:
encode = []
for i in corpus : 

  token = tokenizer.texts_to_sequences([i])[0]
  encode.append(token)


 



In [12]:
encode 

[[10],
 [11, 2, 1],
 [12, 13, 14],
 [15],
 [16, 17],
 [18],
 [19, 1, 20],
 [21],
 [22],
 [23, 1],
 [24, 25],
 [4, 5, 2, 1, 3],
 [4, 2, 8, 5],
 [9, 2, 1, 3],
 [6, 1, 26, 27, 28],
 [6, 1, 29, 30],
 [2, 1, 31, 32],
 [2, 1, 3, 7],
 [9, 6, 1, 3, 7],
 [4, 2, 8, 5, 7]]

In [13]:
max_sequence_len = max([len(x) for x in encode])
input_sequences = np.array(pad_sequences(encode , maxlen=max_sequence_len, padding='pre'))

In [14]:
new_encode = input_sequences 

In [15]:
new_encode 

array([[ 0,  0,  0,  0, 10],
       [ 0,  0, 11,  2,  1],
       [ 0,  0, 12, 13, 14],
       [ 0,  0,  0,  0, 15],
       [ 0,  0,  0, 16, 17],
       [ 0,  0,  0,  0, 18],
       [ 0,  0, 19,  1, 20],
       [ 0,  0,  0,  0, 21],
       [ 0,  0,  0,  0, 22],
       [ 0,  0,  0, 23,  1],
       [ 0,  0,  0, 24, 25],
       [ 4,  5,  2,  1,  3],
       [ 0,  4,  2,  8,  5],
       [ 0,  9,  2,  1,  3],
       [ 6,  1, 26, 27, 28],
       [ 0,  6,  1, 29, 30],
       [ 0,  2,  1, 31, 32],
       [ 0,  2,  1,  3,  7],
       [ 9,  6,  1,  3,  7],
       [ 4,  2,  8,  5,  7]], dtype=int32)

In [33]:
d = []
for i in new_encode:
  c = i.astype("float32")
  d.append(c)

new_encode = d

In [ ]:
for i in range(len(b)):
  print(b[i]["tag"])

greeting
goodbye
thanks
hours
payments
opentoday


In [16]:
#predictions 
y_train = [0,0,0,0,0,1,1,1,2,2,2,3,3,3,4,4,4,5,5,5]

In [17]:
len(y_train) 

20

In [18]:
y_train_cat = tf.keras.utils.to_categorical(
    y_train, num_classes = 6 , dtype='float32'
)

In [19]:
y_train_cat

array([[1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)

# shuffle  data 


In [36]:
shuf = []
for i in range(len(new_encode)):
  shuf.append([new_encode[i] , y_train_cat[i]])

In [37]:
import random
random.shuffle(shuf)

In [38]:
shuf

[[array([ 6.,  1., 26., 27., 28.], dtype=float32),
  array([0., 0., 0., 0., 1., 0.], dtype=float32)],
 [array([4., 2., 8., 5., 7.], dtype=float32),
  array([0., 0., 0., 0., 0., 1.], dtype=float32)],
 [array([0., 9., 2., 1., 3.], dtype=float32),
  array([0., 0., 0., 1., 0., 0.], dtype=float32)],
 [array([ 0.,  0., 11.,  2.,  1.], dtype=float32),
  array([1., 0., 0., 0., 0., 0.], dtype=float32)],
 [array([ 0.,  0.,  0., 16., 17.], dtype=float32),
  array([1., 0., 0., 0., 0., 0.], dtype=float32)],
 [array([4., 5., 2., 1., 3.], dtype=float32),
  array([0., 0., 0., 1., 0., 0.], dtype=float32)],
 [array([0., 2., 1., 3., 7.], dtype=float32),
  array([0., 0., 0., 0., 0., 1.], dtype=float32)],
 [array([ 0.,  0.,  0., 23.,  1.], dtype=float32),
  array([0., 0., 1., 0., 0., 0.], dtype=float32)],
 [array([ 0.,  6.,  1., 29., 30.], dtype=float32),
  array([0., 0., 0., 0., 1., 0.], dtype=float32)],
 [array([ 0.,  0.,  0.,  0., 10.], dtype=float32),
  array([1., 0., 0., 0., 0., 0.], dtype=float32)],


In [39]:
# train test splits 

X_train = []
y_train = []

for i in range(len(shuf)):
  X_train.append(shuf[i][0])
  y_train.append(shuf[i][1])


In [44]:
X_train = np.array(X_train)
y_train = np.array(y_train)

In [47]:
model1 = tf.keras.Sequential([
    tf.keras.layers.Embedding(total_words, 32 , input_length= max_sequence_len ),
    tf.keras.layers.LSTM(32),
    tf.keras.layers.Dense(6, activation="softmax")
])

Both, categorical cross entropy and sparse categorical cross entropy have the same loss function which you have mentioned above. The only difference is the format in which you mention Yi (i,e true labels).

If your Yi's are one-hot encoded, use categorical_crossentropy. Examples (for a 3-class classification): [1,0,0] , [0,1,0], [0,0,1]

But if your Yi's are integers, use sparse_categorical_crossentropy. Examples for above 3-class classification problem: [1] , [2], [3]


https://stats.stackexchange.com/questions/326065/cross-entropy-vs-sparse-cross-entropy-when-to-use-one-over-the-other

In [48]:
model1.compile(loss="categorical_crossentropy",optimizer="rmsprop",metrics=['acc'])

In [49]:
model1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 5, 32)             1056      
_________________________________________________________________
lstm (LSTM)                  (None, 32)                8320      
_________________________________________________________________
dense (Dense)                (None, 6)                 198       
Total params: 9,574
Trainable params: 9,574
Non-trainable params: 0
_________________________________________________________________


In [51]:
model1.fit(X_train , y_train , epochs= 100)

Epoch 1/100
1/1 [==============================] - 0s 5ms/step - loss: 1.7823 - acc: 0.3500
Epoch 2/100
1/1 [==============================] - 0s 6ms/step - loss: 1.7754 - acc: 0.2500
Epoch 3/100
1/1 [==============================] - 0s 6ms/step - loss: 1.7689 - acc: 0.2500
Epoch 4/100
1/1 [==============================] - 0s 7ms/step - loss: 1.7625 - acc: 0.2500
Epoch 5/100
1/1 [==============================] - 0s 7ms/step - loss: 1.7559 - acc: 0.2500
Epoch 6/100
1/1 [==============================] - 0s 7ms/step - loss: 1.7490 - acc: 0.2500
Epoch 7/100
1/1 [==============================] - 0s 7ms/step - loss: 1.7417 - acc: 0.2500
Epoch 8/100
1/1 [==============================] - 0s 7ms/step - loss: 1.7340 - acc: 0.2500
Epoch 9/100
1/1 [==============================] - 0s 7ms/step - loss: 1.7258 - acc: 0.2500
Epoch 10/100
1/1 [==============================] - 0s 7ms/step - loss: 1.7171 - acc: 0.2500
Epoch 11/100
1/1 [==============================] - 0s 7ms/step - loss: 1.7079 

In [52]:
model2 = tf.keras.models.Sequential([
                                  tf.keras.layers.Embedding(total_words, 32 , input_length= max_sequence_len),
                                  tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
                                  tf.keras.layers.Dense(64,activation= "relu"),
                                  tf.keras.layers.Dense(6 , activation="softmax")

])
model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [53]:
model2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 5, 32)             1056      
_________________________________________________________________
bidirectional (Bidirectional (None, 128)               49664     
_________________________________________________________________
dense_1 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 390       
Total params: 59,366
Trainable params: 59,366
Non-trainable params: 0
_________________________________________________________________


In [55]:
model2.fit(X_train , y_train , epochs= 100)

Epoch 1/100
1/1 [==============================] - 0s 7ms/step - loss: 1.7831 - accuracy: 0.4000
Epoch 2/100
1/1 [==============================] - 0s 6ms/step - loss: 1.7780 - accuracy: 0.3500
Epoch 3/100
1/1 [==============================] - 0s 6ms/step - loss: 1.7731 - accuracy: 0.3000
Epoch 4/100
1/1 [==============================] - 0s 6ms/step - loss: 1.7679 - accuracy: 0.3000
Epoch 5/100
1/1 [==============================] - 0s 6ms/step - loss: 1.7624 - accuracy: 0.3000
Epoch 6/100
1/1 [==============================] - 0s 6ms/step - loss: 1.7563 - accuracy: 0.3000
Epoch 7/100
1/1 [==============================] - 0s 6ms/step - loss: 1.7496 - accuracy: 0.3000
Epoch 8/100
1/1 [==============================] - 0s 5ms/step - loss: 1.7423 - accuracy: 0.3000
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 1.7342 - accuracy: 0.3000
Epoch 10/100
1/1 [==============================] - 0s 7ms/step - loss: 1.7254 - accuracy: 0.3000
Epoch 11/100
1/1 [===========

prediction 

In [117]:
#token_list = tokenizer.texts_to_sequences([corpus[2]])[0]
def process(x):
  token_list = tokenizer.texts_to_sequences([x])
  input_sequences = np.array(pad_sequences(token_list , maxlen=max_sequence_len, padding='pre'))
  input_sequences = np.array([input_sequences[0].astype("float32")])
  return input_sequences

def num(x):
  return random.randint(0,x-1)



In [120]:
bot = True 

while bot :
  print("..")
  x = input()
  if x == "quit":
    break
  else:  
    x = process(x)
    x = model2.predict(x)
    x = np.argmax(x[0])
    if x == 0 :
      b = store["intents"][0]["responses"]
      reply = num(len(b))
      print(b[reply])
        
    elif x == 1 :

      b = store["intents"][1]["responses"]
      reply = num(len(b))
      print(b[reply])
        
    elif x == 2 :

      b = store["intents"][2]["responses"]
      reply = num(len(b))
      print(b[reply])
        
    elif x == 3 :
      b = store["intents"][3]["responses"]
      reply = num(len(b))
      print(b[reply])
        
    elif x == 4 :
      b = store["intents"][4]["responses"]
      reply = num(len(b))
      print(b[reply])
      
    else :
      b = store["intents"][5]["responses"]
      reply = num(len(b))
      print(b[reply])


  


..
helloo
Good to see you again
..
can u take payments
Happy to help!
..
nicee
Hello, thanks for visiting
..
goodbye
Bye! Come back again soon.
..
hahhahahahh
Hi there, how can I help?
..
quit
